PBI.Web/Models/ErrorViewModel.cs
using System;

namespace PBI.Web.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

PBI.Web/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using PBI.Web.Models;

namespace PBI.Web.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        public IActionResult Test()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

PBI.Web/Controllers/LetterController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Http;
using Kendo.DynamicLinqCore;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using PBI.Model.Secretariat;
using PBI.Service.IService;

namespace PBI.Web.Controllers
{
    public class LetterController : Controller
    {
        private readonly ILetterService _letterService;
        
        public LetterController(ILetterService letterService)
        {
            _letterService = letterService;
        }
        
        public DataSourceResult GetAllData()
        {
            var item = System.Net.WebUtility.UrlDecode(Request.QueryString.ToString()
                .Remove(0, 1));
            var request = JsonConvert.DeserializeObject<DataSourceRequest>(item);
           
            var test = _letterService.GetAll()
                .ToDataSourceResult(request.Take, request.Skip, request.Sort, request.Filter);
            return test;
        }
        
        [HttpPost] // Add it to fix this error: The requested resource does not support http method 'PUT'
        public IActionResult UpdateLetter([FromBody]Letter letter)
        {
            var item = _letterService.Get(r => r.LetterId == 1).FirstOrDefault();
            if (item == null)
                return BadRequest();
            
            //if (!ModelState.IsValid || id != letter.ID)
               // return new HttpResponseMessage(HttpStatusCode.BadRequest);

            //ProductDataSource.LatestProducts[item.Index] = product;
            return Json(new DataSourceResult {Data = new[] {item}});
        }
        
        // GET
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Create()
        {
            return View();
        }
        
    }
}

PBI.Web/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    
       
</div>
   

PBI.Web/Views/Home/Test.cshtml
@{
    ViewData["Title"] = "Test Page";
}

<div>
    test page
</div>

PBI.Web/Views/Letter/Create.cshtml
@{
    ViewBag.Title = "title";
    Layout = "_Layout";
}

<h2>title</h2>

PBI.Web/Views/Letter/Index.cshtml
@{
    ViewBag.Title = "نامه";
}
<div class="card">
    <div class="card-header">
        <div class="row">
            <div class="col-md-6">
                لیست نامه ها
            </div>
            <div class="col-md-6">
                <a class="btn btn-danger float-left" asp-area="" asp-controller="Letter" asp-action="Create">نامه جدید</a>
            </div>
        </div>
    </div>
    <div class="card-body">
        <div class="row">
            <div class="col-md-12">
                <div id="letter-table">
                    <div class="k-rtl">
                        <div id="report-grid" style="text-align: right"></div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

@section Scripts
{
    <script src="~/js/kendo/initConfig.js"></script>
    <script src="~/js/api/letter.js"></script>

    <script type="x/kendo-template" id="page-template-pdf">
        <div class="" dir="rtl">
            <div class="">
                <div style="float: right">Page #: pageNum # of #: totalPages #</div>
                Multi-page grid with automatic page breaking
            </div>
            <div class="watermark">KENDO UI</div>
            <div class="footer">
                Page #: pageNum # of #: totalPages #
            </div>
        </div>
    </script>
    <script id="toolbarTemplate" type="text/x-kendo-template">
        <a class="k-button" href="\#" onclick="alert('gridState: ' + getCurrentGridFilters());">نوار ابزار سفارشي</a>
    </script>

}

PBI.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"]</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    
    <link href="/css/kendo/kendo.common.min.css" rel="stylesheet" type="text/css" />
    <link href="/css/kendo/kendo.material.min.css" rel="stylesheet" type="text/css"  />
    <link href="/css/kendo/kendo.rtl.min.css" rel="stylesheet"/>
    
    <link rel="stylesheet" href="~/css/site.css"  asp-append-version="true"/>
    <style>
        
    </style>
</head>
<body>
<header>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm 
                  border-bottom box-shadow mb-3"
         style="background-color: #3b3c3e !important;">
        <div class="container" dir="rtl">   
            <a style="font-size: x-large;" class="navbar-brand" href="#">صدور نامه</a>             
            <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                <ul class="navbar-nav flex-grow-1">
                    <li class="nav-item ">
                        <a class="nav-link navbar-collapse" asp-area="" asp-controller="Home" asp-action="Index">صدور نامه</a>
                    </li>
                    <div class="vdivider"></div>
                    <li class="nav-item ">
                        <a class="nav-link" asp-area="" asp-controller="Letter" asp-action="Index">لیست نامه ها</a>
                    </li>                        
                </ul>
            </div>
        </div>
    </nav>
</header>
<div dir="rtl" style="text-align: right;">
    @RenderBody()
</div>

<footer class="border-top footer text-muted" 
        style="background-color: #3b3c3e;
                text-align: center;">
    <div style="color: gray;text-align: center;">
        تمام حقوق برای شرکت پردازش اطلاعات  محفوظ است
    </div>
</footer>
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script src="~/js/site.js" asp-append-version="true"></script>

<script src="~/js/kendo/jszip.min.js" ></script>
<script src="~/js/kendo/kendo.all.min.js" ></script>
<script src="~/js/kendo/cultures/kendo.culture.fa-IR.js" asp-append-version="true"></script>
<script src="~/js/kendo/cultures/kendo.culture.fa.js" asp-append-version="true"></script>
<script src="~/js/kendo/messages/kendo.messages.en-US.min.js" ></script>
<script src="~/js/kendo/cultures/moment.min.js" ></script>
<script src="~/js/kendo/cultures/moment-jalaali.js" ></script>
<script src="~/js/kendo/messages/kendo.fa-IR.js" asp-append-version="true"></script>
<script src="~/js/kendo/pako_deflate.min.js" ></script>
<script src="~/js/PersianDatePicker.min.js"></script>

@RenderSection("Scripts", required: false) 
@* @section Scripts {
        @{ await Html.RenderPartialAsync("_ValidationScriptsPartial"); }
    }*@
</body>
</html>